name: CI
on: [push]

env:
  MAINNET_URL: ${{ secrets.MAINNET_URL }}
  MAINNET_PK: ${{ secrets.MAINNET_PK }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

jobs:
  test:
    name: hardhat tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16

      - name: install node deps
        run: yarn install --frozen-lockfile

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip

      - name: install python deps
        run: pip install -r requirements.txt

      - name: check formatting
        run: yarn check:format

      - name: test
        run: yarn test
